export const wwePlayers = [
  {
    id: 1,
    name: "John Cena",
    rank: 2,
    height: "185",
    weight: 251,
    chest: "127",
    biceps: "53",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/cena.png",
    audio: "",
    arcade_id: 1,
    points: 25,
  },
  {
    id: 2,
    name: "The Undertaker",
    rank: 1,
    height: "208",
    weight: 309,
    chest: "130",
    biceps: "55",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/undertaker.png",
    audio: "",
    arcade_id: 1,
    points: 30,
  },
  {
    id: 3,
    name: "Triple H (HHH)",
    rank: 5,
    height: "193",
    weight: 255,
    chest: "122",
    biceps: "51",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/hhh.png",
    audio: "",
    arcade_id: 1,
    points: 20,
  },
  {
    id: 4,
    name: "Big Show",
    rank: 10,
    height: "213",
    weight: 383,
    chest: "150",
    biceps: "60",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/bigshow.png",
    audio: "",
    arcade_id: 1,
    points: 15,
  },
  {
    id: 5,
    name: "The Great Khali",
    rank: 15,
    height: "216",
    weight: 347,
    chest: "147",
    biceps: "58",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/khali.png",
    audio: "",
    arcade_id: 1,
    points: 10,
  },
  {
    id: 6,
    name: "Brock Lesnar",
    rank: 4,
    height: "191",
    weight: 286,
    chest: "130",
    biceps: "55",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/lesnar.png",
    audio: "",
    arcade_id: 1,
    points: 20,
  },
  {
    id: 7,
    name: "CM Punk",
    rank: 8,
    height: "185",
    weight: 218,
    chest: "120",
    biceps: "50",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/punk.png",
    audio: "",
    arcade_id: 1,
    points: 15,
  },
  {
    id: 8,
    name: "Roman Reigns",
    rank: 6,
    height: "191",
    weight: 265,
    chest: "128",
    biceps: "54",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/roman.png",
    audio: "",
    arcade_id: 1,
    points: 20,
  },
  {
    id: 9,
    name: "Rikishi",
    rank: 14,
    height: "185",
    weight: 425,
    chest: "155",
    biceps: "62",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/rikhishi.png",
    audio: "",
    arcade_id: 1,
    points: 10,
  },
  {
    id: 10,
    name: "Rey Mysterio",
    rank: 9,
    height: "168",
    weight: 175,
    chest: "115",
    biceps: "47",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/ray.png",
    audio: "",
    arcade_id: 1,
    points: 15,
  },
  {
    id: 11,
    name: "Edge",
    rank: 7,
    height: "196",
    weight: 241,
    chest: "125",
    biceps: "52",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/edge.png",
    audio: "",
    arcade_id: 1,
    points: 15,
  },
  {
    id: 12,
    name: "Kane",
    rank: 11,
    height: "213",
    weight: 323,
    chest: "148",
    biceps: "57",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/kane.png",
    audio: "",
    arcade_id: 1,
    points: 15,
  },
  {
    id: 13,
    name: "Sin Cara",
    rank: 16,
    height: "170",
    weight: 198,
    chest: "118",
    biceps: "48",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/sincara.png",
    audio: "",
    arcade_id: 1,
    points: 10,
  },
  {
    id: 14,
    name: "Sting",
    rank: 13,
    height: "189",
    weight: 250,
    chest: "127",
    biceps: "53",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/sting.png",
    audio: "",
    arcade_id: 1,
    points: 10,
  },
  {
    id: 15,
    name: "Umaga",
    rank: 17,
    height: "193",
    weight: 350,
    chest: "145",
    biceps: "59",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/umanga.png",
    audio: "",
    arcade_id: 1,
    points: 10,
  },
  {
    id: 16,
    name: "The Rock",
    rank: 3,
    height: "196",
    weight: 260,
    chest: "125",
    biceps: "52",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/rock.png",
    audio: "",
    arcade_id: 1,
    points: 25,
  },
  {
    id: 17,
    name: "Shawn Michaels",
    rank: 12,
    height: "185",
    weight: 225,
    chest: "120",
    biceps: "50",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/shawn.png",
    audio: "",
    arcade_id: 1,
    points: 10,
  },
  {
    id: 18,
    name: "Booker T",
    rank: 18,
    height: "190",
    weight: 256,
    chest: "122",
    biceps: "52",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/booker.png",
    audio: "",
    arcade_id: 1,
    points: 5,
  },
  {
    id: 19,
    name: "Batista",
    rank: 19,
    height: "198",
    weight: 290,
    chest: "132",
    biceps: "56",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/batista.png",
    audio: "",
    arcade_id: 1,
    points: 5,
  },
  {
    id: 20,
    name: "Randy Orton",
    rank: 20,
    height: "196",
    weight: 250,
    chest: "124",
    biceps: "53",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/randy.png",
    audio: "",
    arcade_id: 1,
    points: 5,
  },
  {
    id: 21,
    name: "Goldberg",
    rank: 21,
    height: "193",
    weight: 285,
    chest: "131",
    biceps: "55",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/gold.png",
    audio: "",
    arcade_id: 1,
    points: 5,
  },
  {
    id: 22,
    name: "Chris Jericho",
    rank: 22,
    height: "183",
    weight: 227,
    chest: "119",
    biceps: "49",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/chris.png",
    audio: "",
    arcade_id: 1,
    points: 5,
  },
  {
    id: 23,
    name: "Eddie Guerrero",
    rank: 23,
    height: "187",
    weight: 257,
    chest: "129",
    biceps: "52",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/eddie.png",
    audio: "",
    arcade_id: 1,
    points: 5,
  },
  {
    id: 24,
    name: "Kurt Angle",
    rank: 24,
    height: "183",
    weight: 240,
    chest: "121",
    biceps: "51",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/kurt.png",
    audio: "",
    arcade_id: 1,
    points: 5,
  },
  {
    id: 25,
    name: "AJ Styles",
    rank: 25,
    height: "180",
    weight: 218,
    chest: "118",
    biceps: "48",
    gender: "male",
    image:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/cards/aj.png",
    audio: "",
    arcade_id: 1,
    points: 5,
  },
];

export const arc = [
  {
    title: "WWE",
    cover:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/games/wwe.png",
    id: 1,
    status: true,
    audio: "",
    rules:
      "Players use cards representing WWE wrestlers, each with attributes like height, weight, chest, and biceps. Players can engage in matches by comparing these attributes, and the wrestler with superior stats wins the round.",
    description:
      "This card game is based on World Wrestling Entertainment, featuring famous wrestlers like John Cena, The Undertaker, and Brock Lesnar. It captures the excitement and drama of professional wrestling.",
    points: "",
  },
  {
    title: "Pokemon",
    cover:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/games/pokemon.png",
    id: 2,
    status: false,
    audio: "",
    rules:
      "Players use Pokemon cards, each with unique abilities, strengths, and weaknesses. The game involves strategic use of these cards to battle opponents, with the aim to 'catch them all'.",
    description:
      "Inspired by the popular Pokemon franchise, this card game involves collecting and battling with various Pokemon, each with its own set of skills and power levels.",
    points: "",
  },
  {
    title: "Cricket",
    cover:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/games/cricklet.png",
    id: 3,
    status: false,
    audio: "",
    rules:
      "Cards represent cricket players with skills like batting, bowling, and fielding. Players form teams and simulate cricket matches, with outcomes based on players' stats and strategic decisions.",
    description:
      "A card game based on the sport of cricket. It features cards of famous cricketers from around the world, emphasizing their playing style and statistics.",
    points: "",
  },
  {
    title: "Football",
    cover:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/games/footbal.png",
    id: 4,
    status: false,
    audio: "",
    rules:
      "Each card represents a football player with attributes like speed, strength, and skill. Players form teams and compete in matches, with outcomes determined by player stats and card synergies.",
    description:
      "This card game is centered around football, featuring legendary players and their specific skills. It allows players to build their dream team and compete in tactical matches.",
    points: "",
  },
  {
    title: "Beyblade",
    cover:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/games/beyblade.png",
    id: 5,
    status: false,
    audio: "",
    rules:
      "Cards represent different Beyblades with attributes like speed, balance, and power. Players 'launch' their Beyblades in battles, with victory determined by the combination of these attributes.",
    description:
      "Based on the Beyblade series, this card game involves battles between spinning tops known as Beyblades. Each card represents a Beyblade with unique characteristics.",
    points: "",
  },
  {
    title: "Naruto",
    cover:
      "https://ds-storage.sgp1.cdn.digitaloceanspaces.com/ethindia/games/naruto.png",
    id: 6,
    status: false,
    audio: "",
    rules:
      "Cards represent characters from the Naruto universe, each with unique ninja skills and abilities. Players use these cards to engage in strategic battles, mimicking the anime's storyline.",
    description:
      "This game draws from the Naruto anime, featuring ninjas with special abilities. Players can recreate famous battles from the series or forge their own ninja adventures.",
    points: "",
  },
];
