import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { WagmiHoc } from "../../utils/wagmi";
import { LightNodeProvider } from "@waku/react";
import { Protocols } from "@waku/sdk";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <WagmiHoc>
        <LightNodeProvider
          options={{ defaultBootstrap: true }}
          protocols={[Protocols.Store, Protocols.Filter, Protocols.LightPush]}
        >
          <body className={inter.className}>{children}</body>
        </LightNodeProvider>
      </WagmiHoc>
    </html>
  );
}
